### ISSUE TITLE
Cannot read property 'Properties' of undefined

### ISSUE THREAD

**Issue by manjirinamjoshi** [jacob-meacham/serverless-plugin-bind-deployment-id#11]
Hello,

I am getting this error for "sls deploy --stage dev" -

TypeError: Cannot read property 'Properties' of undefined
    at BindDeploymentId.fixUpDeploymentStage (/et/repo/serverless/channel/node_modules/serverless-plugin-bind-deployment-id/lib/index.js:70:32)
    at BindDeploymentId.bindDeploymentId (/et/repo/serverless/channel/node_modules/serverless-plugin-bind-deployment-id/lib/index.js:48:35)

My serverless.yml has functions and API Gateway resources and methods.

When I decide to have a trigger for atleast 1 function then this error doesnt appear.
But, if none of my lambda functions have a trigger then this errors pops up.

`service: channel-service

plugins:
  - serverless-mocha-plugin
  - serverless-dynamodb-local
  - serverless-plugin-stage-variables
  - serverless-plugin-bind-deployment-id
  - serverless-api-compression
  - serverless-pseudo-parameters
  - serverless-offline #must be last on the list
custom:
  tableName: 'channels-table-${self:provider.stage}'
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
  customDomain:
    basePath: 'fa'
    domainName: test.enterpriseticketing.com
    stage: ${opt:stage, self:provider.stage}
    createRoute53Record: true

  contentEncoding:
    contentCompression: 100 # Minimum body size required for compression in bytes  

  region: ${opt:region, self:provider.region}
provider:
  name: aws
  runtime: nodejs8.10 #lastest that AWS supports
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["ChannelsDynamoDBTable", "Arn"] }
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource:
        - "*"
  environment:
    CHANNELS_TABLE: ${self:custom.tableName}
    API_GATEWAY_CACHE_TTL: 900 # 15mins

#below items are marked to api gateway endpoints, we want these to be specific
functions:
  readByChannelCode:
    handler: src/index.readByChannelCode
  readByChannelId:
    handler: src/index.readByChannelId
  readAll:
    handler: src/index.readAll
  createChannel:
    handler: src/index.createChannel

  updateChannel:
    handler: src/index.updateChannel  

resources:
  Resources:
    ChannelsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: status
            AttributeType: S
          -
            AttributeName: channelCd
            AttributeType: S
          -
            AttributeName: pdiChannelId
            AttributeType: N
          -
            AttributeName: organizationId
            AttributeType: N
        KeySchema:
          -
            AttributeName: channelCd
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
        GlobalSecondaryIndexes:
        - IndexName: channelId-index
          KeySchema:
          - AttributeName: pdiChannelId
            KeyType: HASH
          Projection:
              ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: status-index
          KeySchema:
          - AttributeName: status
            KeyType: HASH
          - AttributeName: organizationId
            KeyType: RANGE
          Projection:
              ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
    ApiGatewayStage:
      Type: 'AWS::ApiGateway::Stage'
      Properties:
        RestApiId:
          Ref: ApiGatewayRestApi
        CacheClusterEnabled: true
        CacheClusterSize: "0.5"
        DeploymentId:
          Ref: __deployment__
        MethodSettings:
          - ResourcePath: "/*"
            HttpMethod: "*"
            CachingEnabled: false
            MetricsEnabled: true
          - ResourcePath: "/~1v1~1channels~1{channelCode}"
            HttpMethod: "GET"
            CacheDataEncrypted: false
            CacheTtlInSeconds: ${self:provider.environment.API_GATEWAY_CACHE_TTL}
            CachingEnabled: true
          - ResourcePath: "/~1v1~1channels"
            HttpMethod: "GET"
            CacheDataEncrypted: false
            CacheTtlInSeconds: ${self:provider.environment.API_GATEWAY_CACHE_TTL}
            CachingEnabled: true
    BaseResource:
      Type: AWS::ApiGateway::Resource
      Properties:
        ParentId:
          Fn::GetAtt:
            - ApiGatewayRestApi # our default Rest API logical ID
            - RootResourceId
        PathPart: "v1" # the endpoint in your API that is set as proxy
        RestApiId:
          Ref: ApiGatewayRestApi
    ProxyResource:
      Type: AWS::ApiGateway::Resource
      Properties:
        ParentId: 
          Ref: BaseResource
          #Fn::GetAtt:
          #  - ApiGatewayRestApi # our default Rest API logical ID
          #  - RootResourceId
        PathPart: "channels" # the endpoint in your API that is set as proxy
        RestApiId:
          Ref: ApiGatewayRestApi
    ReadByChannelIdProxyResource:
      Type: AWS::ApiGateway::Resource
      Properties:
        ParentId: 
          Ref: ProxyResource
        PathPart: "id" # the endpoint in your API that is set as proxy
        RestApiId:
          Ref: ApiGatewayRestApi
    ReadByChannelCodeResource:
      Type: AWS::ApiGateway::Resource
      Properties:
        ParentId: 
          Ref: ProxyResource
        PathPart: "{channelCode}" # the endpoint in your API that is set as proxy
        RestApiId:
          Ref: ApiGatewayRestApi
    ReadByChannelIdResource:
      Type: AWS::ApiGateway::Resource
      Properties:
        ParentId: 
          Ref: ReadByChannelIdProxyResource
        PathPart: "{channelId}" # the endpoint in your API that is set as proxy
        RestApiId:
          Ref: ApiGatewayRestApi
    ReadAllApiGatewayMethod:
      Type: 'AWS::ApiGateway::Method'
      Properties:
        AuthorizationType: "NONE"
        HttpMethod: "GET"
        ResourceId:
          Ref: ProxyResource
        RestApiId: 
          Ref: ApiGatewayRestApi
        RequestParameters:
          method.request.querystring.status: false
          method.request.querystring.businessOrgId: false
        Integration:
          IntegrationHttpMethod: GET
          Type: AWS_PROXY
          Uri: arn:aws:apigateway:#{AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:#{AWS::AccountId}:function:${self:service}-${opt:stage}-readAll/invocations
          PassthroughBehavior: WHEN_NO_MATCH
          CacheKeyParameters: 
            - method.request.querystring.status
            - method.request.querystring.businessOrgId
          RequestParameters: 
            integration.request.querystring.status: method.request.querystring.status
            integration.request.querystring.businessOrgId: method.request.querystring.businessOrgId
    ReadByChannelCodeApiGatewayMethod:
      Type: 'AWS::ApiGateway::Method'
      Properties:
        AuthorizationType: "NONE"
        HttpMethod: "GET"
        ResourceId:
          Ref: ReadByChannelCodeResource
        RestApiId: 
          Ref: ApiGatewayRestApi
        RequestParameters:
          method.request.path.channelCode: true
        Integration:
          IntegrationHttpMethod: POST
          Type: AWS_PROXY
          Uri: arn:aws:apigateway:#{AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:#{AWS::AccountId}:function:${self:service}-${opt:stage}-readByChannelCode/invocations
          PassthroughBehavior: WHEN_NO_MATCH
          CacheKeyParameters: 
            - method.request.path.channelCode
          RequestParameters: 
            integration.request.path.channelCode: method.request.path.channelCode

    ReadByChannelIdApiGatewayMethod:
      Type: 'AWS::ApiGateway::Method'
      Properties:
        AuthorizationType: "NONE"
        HttpMethod: "GET"
        ResourceId:
          Ref: ReadByChannelIdResource
        RestApiId: 
          Ref: ApiGatewayRestApi
        RequestParameters:
          method.request.path.channelId: true
        Integration:
          IntegrationHttpMethod: POST
          Type: AWS_PROXY
          Uri: arn:aws:apigateway:#{AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:#{AWS::AccountId}:function:${self:service}-${opt:stage}-readByChannelId/invocations
          PassthroughBehavior: WHEN_NO_MATCH
          CacheKeyParameters: 
            - method.request.path.channelId
          RequestParameters: 
            integration.request.path.channelId: method.request.path.channelId

    CreateChannelApiGatewayMethod:
      Type: 'AWS::ApiGateway::Method'
      Properties:
        AuthorizationType: "NONE"
        HttpMethod: "POST"
        ResourceId:
          Ref: ProxyResource
        RestApiId: 
          Ref: ApiGatewayRestApi
        Integration:
          IntegrationHttpMethod: POST
          Type: AWS_PROXY
          Uri: arn:aws:apigateway:#{AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:#{AWS::AccountId}:function:${self:service}-${opt:stage}-createChannel/invocations
          PassthroughBehavior: WHEN_NO_MATCH
    UpdateChannelApiGatewayMethod:
      Type: 'AWS::ApiGateway::Method'
      Properties:
        AuthorizationType: "NONE"
        HttpMethod: "PATCH"
        ResourceId:
          Ref: ReadByChannelCodeResource
        RestApiId: 
          Ref: ApiGatewayRestApi
        RequestParameters:
          method.request.path.channelCode: true
        Integration:
          IntegrationHttpMethod: POST
          Type: AWS_PROXY
          Uri: arn:aws:apigateway:#{AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:#{AWS::AccountId}:function:${self:service}-${opt:stage}-updateChannel/invocations
          PassthroughBehavior: WHEN_NO_MATCH

    ReadByChannelCodeLambdaInvokePermission:
      Type: AWS::Lambda::Permission
      Properties:
        #FunctionName: GetAtt 
        #  - readByChannelCode
        #  - arn:aws:lambda:us-west-2:#{AWS::AccountId}:function:${self:service}-${opt:stage}-readByChannelCode
        FunctionName: "${self:service}-${opt:stage}-readByChannelCode" #arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-readByChannelCode
        Action: 'lambda:InvokeFunction'
        Principal: apigateway.amazonaws.com
      DependsOn: "ApiGatewayStage"
    ReadByChannelIdLambdaInvokePermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: "${self:service}-${opt:stage}-readByChannelId" 
        Action: 'lambda:InvokeFunction'
        Principal: apigateway.amazonaws.com
      DependsOn: "ApiGatewayStage"
    ReadAllLambdaInvokePermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: "${self:service}-${opt:stage}-readAll" 
        Action: 'lambda:InvokeFunction'
        Principal: apigateway.amazonaws.com
      DependsOn: "ApiGatewayStage"
      
    `

**Comment by jacob-meacham** [comment]
Hi @manjirinamjoshi thanks for the bug report! The issue here is that Serverless only creates a resource of type AWS::ApiGateway::Deployment when you actually hook up a function to an endpoint. Without that, this plugin doesn't really serve much of a purpose. However, to fix the issue, you could log a warning and return out of bindDeploymentId in src/index if the deploymentId is unset. Happy to approve a PR if you put on up. Thanks again!

**Comment by manjirinamjoshi** [comment]
Thank you so much for your reply. And, my apologies, I am very new to serverless world.
On my local, tried to return out if bindDeploymentId, but ran into this error -

Unresolved resource dependencies [ApiGatewayRestApi] in the Resources block of the template

Any thoughts ?

Thank you

Sincerely,
Manjiri

**Comment by developersatish** [comment]
`
E:\Work\Satish\serverless\my-app\node_modules\webpack-cli\bin\config-yargs.js:136
                                describe: optionsSchema.definitions.output.properties.path.description,

  ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (E:\Work\Satish\serverless\my-app\node_modules\webpack-cli\bin\config-yargs.js:136:48)
    at E:\Work\Satish\serverless\my-app\node_modules\webpack-cli\bin\webpack.js:59:27
    at Object.<anonymous> (E:\Work\Satish\serverless\my-app\node_modules\webpack-cli\bin\webpack.js:514:3)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (E:\Work\Satish\serverless\my-app\node_modules\webpack\bin\webpack.js:156:2)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-app@0.0.0 build:server:serverless: `ng run my-app:server:serverless && webpack --config webpack.server.config.js --progress --colors`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-app@0.0.0 build:server:serverless script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SatishPc\AppData\Roaming\npm-cache\_logs\2020-02-24T17_26_44_216Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-app@0.0.0 build:serverless: `npm run build:browser:serverless && npm run build:server:serverless`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-app@0.0.0 build:serverless script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SatishPc\AppData\Roaming\npm-cache\_logs\2020-02-24T17_26_44_264Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-app@0.0.0 build:serverless:deploy: `npm run build:serverless
&& npm run deploy`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-app@0.0.0 build:serverless:deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SatishPc\AppData\Roaming\npm-cache\_logs\2020-02-24T17_26_44_308Z-debug.log
`

**Comment by jacob-meacham** [comment]
Hi @developersatish thanks for the report - can you give me some more information:
* What version of serverless are you running?
* What version of the plugin are you using?
* What other serverless plugins do you have?

**Comment by troybESM** [comment]
I had the same issue, and it was resolved by adding an event.
output from serverless --version
Framework Core: 1.79.0
Plugin: 3.7.1
SDK: 2.3.1
Components: 2.34.6

Plugins and versions:
    "serverless-cloudformation-changesets": "0.0.2",
    "serverless-dependson-plugin": "^1.1.2",
    "serverless-deployment-bucket": "^1.1.2",
    "serverless-plugin-bind-deployment-id": "^1.2.0",
    "serverless-plugin-create-deployment-bucket": "0.0.2",
    "serverless-plugin-tracing": "^2.0.0"

**Comment by rsshilli** [comment]
I just tried to migrate all of my functions from using `http` (API Gateway REST API) to `httpApi` (API Gateway HTTP API) and I got this same error. [Read more here.](https://www.serverless.com/blog/aws-http-api-support)

@troybESM What do you mean by "it was resolved by adding an event"? Where did you add the event to?
